/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddSpotRouteImport } from './routes/add-spot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpotSpotIdRouteImport } from './routes/spot.$spotId'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddSpotRoute = AddSpotRouteImport.update({
  id: '/add-spot',
  path: '/add-spot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotSpotIdRoute = SpotSpotIdRouteImport.update({
  id: '/spot/$spotId',
  path: '/spot/$spotId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-spot': typeof AddSpotRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/update-password': typeof UpdatePasswordRoute
  '/spot/$spotId': typeof SpotSpotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-spot': typeof AddSpotRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/update-password': typeof UpdatePasswordRoute
  '/spot/$spotId': typeof SpotSpotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-spot': typeof AddSpotRoute
  '/admin': typeof AdminRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/update-password': typeof UpdatePasswordRoute
  '/spot/$spotId': typeof SpotSpotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-spot'
    | '/admin'
    | '/explore'
    | '/favorites'
    | '/forgot-password'
    | '/profile'
    | '/register'
    | '/signin'
    | '/update-password'
    | '/spot/$spotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-spot'
    | '/admin'
    | '/explore'
    | '/favorites'
    | '/forgot-password'
    | '/profile'
    | '/register'
    | '/signin'
    | '/update-password'
    | '/spot/$spotId'
  id:
    | '__root__'
    | '/'
    | '/add-spot'
    | '/admin'
    | '/explore'
    | '/favorites'
    | '/forgot-password'
    | '/profile'
    | '/register'
    | '/signin'
    | '/update-password'
    | '/spot/$spotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddSpotRoute: typeof AddSpotRoute
  AdminRoute: typeof AdminRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SigninRoute: typeof SigninRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  SpotSpotIdRoute: typeof SpotSpotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-spot': {
      id: '/add-spot'
      path: '/add-spot'
      fullPath: '/add-spot'
      preLoaderRoute: typeof AddSpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot/$spotId': {
      id: '/spot/$spotId'
      path: '/spot/$spotId'
      fullPath: '/spot/$spotId'
      preLoaderRoute: typeof SpotSpotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddSpotRoute: AddSpotRoute,
  AdminRoute: AdminRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SigninRoute: SigninRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  SpotSpotIdRoute: SpotSpotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
